version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - 15432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./resource:/home/resource
    environment:
      POSTGRES_USER: shimasan
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:6
    container_name: pgadmin4
    ports:
      - 9999:80
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sample@sample.com
      PGADMIN_DEFAULT_PASSWORD: sample1234
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_volume:
    external: true
  pgadmin4_volume:
    external: true
